name: Deploy to NVIDIA Jetson

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for image builder
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image to GHCR
      run: |
        docker buildx build \
          --platform linux/arm64,linux/amd64 \
          --tag ${{ steps.meta.outputs.tags }} \
          --push .
